name: Growth

on:
  schedule:
    # UTC 时间 0 点运行一次
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  growth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'

      - name: Depend install and serve
        env:
          COOKIE: csrf_session_id=e265040d74ee362c1dc84cf1950d4637; _tea_utm_cache_2018={%22utm_source%22:%22gold_browser_extension%22}; _tea_utm_cache_2608={%22utm_source%22:%22gold_browser_extension%22}; __tea_cookie_tokens_2608=%257B%2522web_id%2522%253A%25227323038883054372415%2522%252C%2522user_unique_id%2522%253A%25227323038883054372415%2522%252C%2522timestamp%2522%253A1705027870587%257D; passport_csrf_token=5eb10832e0736f5d2ae17abcff8768f9; passport_csrf_token_default=5eb10832e0736f5d2ae17abcff8768f9; n_mh=Cnh05CH1Mtmld1KnWiQ-4Gqbkf702lUnDliGiTaf92g; sid_guard=66cbd8fede5e608f3babe8029d0f32b6%7C1705279574%7C31536000%7CTue%2C+14-Jan-2025+00%3A46%3A14+GMT; uid_tt=be63a60829937710192fdc070200725a; uid_tt_ss=be63a60829937710192fdc070200725a; sid_tt=66cbd8fede5e608f3babe8029d0f32b6; sessionid=66cbd8fede5e608f3babe8029d0f32b6; sessionid_ss=66cbd8fede5e608f3babe8029d0f32b6; sid_ucp_v1=1.0.0-KDU5MzM0M2RmMGE4MjNjMDdiZjc4YTBlYTY4MGExNzgyZmU0YmJmODEKFwj96oDklY2JARDWgJKtBhiwFDgCQO8HGgJsZiIgNjZjYmQ4ZmVkZTVlNjA4ZjNiYWJlODAyOWQwZjMyYjY; ssid_ucp_v1=1.0.0-KDU5MzM0M2RmMGE4MjNjMDdiZjc4YTBlYTY4MGExNzgyZmU0YmJmODEKFwj96oDklY2JARDWgJKtBhiwFDgCQO8HGgJsZiIgNjZjYmQ4ZmVkZTVlNjA4ZjNiYWJlODAyOWQwZjMyYjY; store-region=cn-gd; store-region-src=uid; msToken=oQu7-41_8fiQpIogOGynZOPMAqhFYfMPDWEQYGSI5biHfo4LUMe9_YjdeTgTnmHqgNzIsKlcXrJF9rdKb5_nG_dl4dbRX9ebYHM8Gsf_6fV9HOuKBcytHrGG6J5NCg==
          EMAIL: ${{ secrets.EMAIL }}
          AUTHORIZATION_CODE: ${{ secrets.AUTHORIZATION_CODE }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
        run: |
          npm install
          npm run serve
